# Generated by Django 4.1.3 on 2022-11-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bistro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_items',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
