# Generated by Django 4.1.3 on 2022-11-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bistro', '0002_alter_menu_items_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_items',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
