# Generated by Django 4.1.3 on 2022-11-11 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bistro', '0003_menu_items_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu_Items',
            new_name='MenuItem',
        ),
    ]
